import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Box } from '@chakra-ui/react'
import AnouncmentBar from '@/components/anounceMent/AnouncmentBar'
import Header from '@/components/header/Header'
import Carousel from '@/components/Carosel/Carousel'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main >
        <Box minH={'100vh'}>
          <AnouncmentBar />
          <Header />
          <Carousel />
        </Box>
      </main>
    </>
  )
}
